### ISSUE TITLE
Illegal (?) character at the end of some sentences

### ISSUE THREAD

**Issue by AngledLuffa** [UniversalDependencies/UD_Portuguese-PetroGold#4]
There are some training sentences with illegal characters at the end of them.  For example:

```
# text = Fonte : Adaptado de Da Mata ( 1993 )                                 |
# sent_id = 398-20160721-MONOGRAFIA_0-91                                       |
10                    PUNCT   _       _       1       punct   _       _
```

According to emacs, the last character in this sentence is 0xF0B7, "not a valid Unicode character" according to online unicode dictionaries

https://www.fileformat.info/info/unicode/char/f0b7/index.htm

Other examples:

```
# text = Fonte : Adaptado de Da Mata ( 1993 ) 
# sent_id = 398-20160721-MONOGRAFIA_0-93

# text = Fonte : Adaptado de Da Mata ( 1993 ) 
# sent_id = 398-20160721-MONOGRAFIA_0-97

# text = Segundo Manichand ( 2002 ) , as vantagens do aquecimento eletromagnético em relação aos métodos convencionais de recuperação térmica são :  É aplicado sem a injeção de qualquer outro fluido no reservatório , evitando o gasto energético e perda de fluido aquecido para zonas de falha ou de alta permeabilidade .  Aplica-se em reservatórios que apresentem problemas de inchamento de argilas em presença de água ou vapor . 
# sent_id = 398-20160721-MONOGRAFIA_0-103

# text = A não-linearidade também inclui efeitos de histerese, onde não só as intensidades de campo corrente influenciam as propriedades físicas do material, mas também a distribuição do campo.  Materiais dispersivos: descreve mudanças na velocidade de uma onda com comprimento de onda.
# sent_id = 398-20160721-MONOGRAFIA_0-175

# text = Para isto , este estudo foi dividido em duas partes :  Teórica : Estudo teórico sobre o aquecimento eletromagnético , solo , poços de petróleo da região nordeste do Brasil , viscosidade , temperatura e dinâmica dos fluidos .
# sent_id = 398-20160721-MONOGRAFIA_0-206
```

Actually, there's quite a few of these, scattered throughout the dataset

**Comment by alvelvis** [comment]
HI @AngledLuffa thanks for noticing.

These characters come from converting PDF to plain text files. I tried to fix their annotation in the sentences in a previous issue but now I see there are still some "misannotations" that I will be fixing. Apart from that, the fact that they are "invalid" characters are a problem for your usage?

**Comment by AngledLuffa** [comment]
Thank you, excellent.  It's not a big problem on our end - them showing up at the end of a sentence was unexpected, but we fixed the bug that exposed.

**Comment by alvelvis** [comment]
I believe there's nothing we can do about the characters themselves, because although they are commonly bullet points in the original PDF files, it is not possible to recover what kind of bullet point each of them is accurately nor can we guarantee that they are bullet points. So we are keeping them as "non-unicode" for now. Removing them is also not adequate because bullet points do convey some meaning...

Thanks for reporting.

**Comment by AngledLuffa** [comment]
I would think picking a standard bullet point to use in such cases would be better than leaving it with characters that mean nothing.  The worst case scenario of picking https://www.compart.com/en/unicode/U+2022 for example instead of the correct bullet point isn't too bad
